create table IF NOT EXISTS FILE(
    HASH STRING(27) NOT NULL PRIMARY KEY, 
    CREATION TIMESTAMPTZ NOT NULL,
    LAST_MODIFIED TIMESTAMPTZ NOT NULL,
    ACTIVE BOOL NOT NULL DEFAULT true,
    REMOVED BOOL NOT NULL DEFAULT false,
    SIZE INT NOT NULL,
    DATA BYTES DEFAULT NULL,
    REF_COUNT INT DEFAULT 1,
    BLOCKS STRING[],
    DONE BOOL DEFAULT false,
)

create table IF NOT EXISTS FILE_OWNER(
    NODE_ID_AND_PATH STRING NOT NULL PRIMARY KEY, 
    CREATION TIMESTAMPTZ NOT NULL,
    LAST_MODIFIED TIMESTAMPTZ NOT NULL,
    ACTIVE BOOL NOT NULL DEFAULT true,
    REMOVED BOOL NOT NULL DEFAULT false,
    FILE_OR_FOLDER STRING[]
)