create table IF NOT EXISTS CLIENT(
    NODE_ID STRING(30) NOT NULL PRIMARY KEY, 
    PUBLIC_KEY BYTES NOT NULL,
    CONTACT_EMAIL STRING(128) NOT NULL,
    EMAIL_VERIFIED BOOL DEFAULT false,
    CREATION TIMESTAMPTZ NOT NULL,
    LAST_MODIFIED TIMESTAMPTZ NOT NULL,
    RANDOM_CODE STRING(8) DEFAULT NULL,
    SEND_TIME TIMESTAMPTZ DEFAULT NULL,
    ACTIVE BOOL NOT NULL DEFAULT true,
    REMOVED BOOL NOT NULL DEFAULT false
);