create table IF NOT EXISTS PROVIDER(
    NODE_ID STRING(30) NOT NULL PRIMARY KEY, 
    PUBLIC_KEY BYTES NOT NULL,
    BILL_EMAIL STRING(128) NOT NULL,
    EMAIL_VERIFIED BOOL DEFAULT false,
    ENCRYPT_KEY BYTES NOT NULL, 
    WALLET_ADDRESS STRING(64) NOT NULL,
    ADDRESS_CHECKSUM STRING(64) DEFAULT NULL,
    UP_BANDWIDTH INT NOT NULL,
    DOWN_BANDWIDTH INT NOT NULL,
    TEST_UP_BANDWIDTH INT NOT NULL,
    TEST_DOWN_BANDWIDTH INT NOT NULL,
    AVAILABILITY FLOAT NOT NULL,
    PORT INT NOT NULL,
    HOST STRING(32) DEFAULT NULL,
    DYNAMIC_DOMAIN STRING(32) DEFAULT NULL,
    STORAGE_VOLUME int[] NOT NULL,
    CREATION TIMESTAMPTZ NOT NULL,
    LAST_MODIFIED TIMESTAMPTZ NOT NULL,
    RANDOM_CODE STRING(8) DEFAULT NULL,
    SEND_TIME TIMESTAMPTZ DEFAULT NULL,
    ACTIVE BOOL NOT NULL DEFAULT true,
    REMOVED BOOL NOT NULL DEFAULT false,
    LAST_CONNECT TIMESTAMPTZ DEFAULT NULL,
    LAST_AVAIL TIMESTAMPTZ DEFAULT NULL,
    VERSION INT DEFAULT 0
);

create table IF NOT EXISTS PROVIDER_DAILY_NETFLOW(
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    NODE_ID STRING(30) NOT NULL REFERENCES PROVIDER (NODE_ID),
    DAY DATE NOT NULL,
    TYPE INT NOT NULL,
    CREATION TIMESTAMPTZ NOT NULL,
    LAST_MODIFIED TIMESTAMPTZ NOT NULL,
    NETFLOW INT NOT NULL default 0,
    FIX_OFFSET INT NOT NULL default 0,
    UNIQUE (NODE_ID,DAY,TYPE)
);


create table IF NOT EXISTS PRIVATE_ALIVE_RECORD(
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    PROVIDER_ID STRING(30) NOT NULL REFERENCES PROVIDER (NODE_ID),
    TIMESTAMP TIMESTAMPTZ NOT NULL,
    TOTAL_FREE_VOLUME INT NOT NULL,
    AVAIL_FILE_SIZE INT NOT NULL,
    VERSION INT DEFAULT 0
);
CREATE INDEX TIMESTAMP ON PRIVATE_ALIVE_RECORD (TIMESTAMP);
