create table IF NOT EXISTS CLIENT(
    NODE_ID STRING(30) NOT NULL PRIMARY KEY, 
    PUBLIC_KEY BYTES NOT NULL,
    CONTACT_EMAIL STRING(128) NOT NULL,
    EMAIL_VERIFIED BOOL DEFAULT false,
    CREATION TIMESTAMPTZ NOT NULL,
    LAST_MODIFIED TIMESTAMPTZ NOT NULL,
    RANDOM_CODE STRING(8) DEFAULT NULL,
    SEND_TIME TIMESTAMPTZ DEFAULT NULL,
    ACTIVE BOOL NOT NULL DEFAULT true,
    REMOVED BOOL NOT NULL DEFAULT false,
    RECHARGE_ADDRESS STRING(64) NOT NULL,
    ADDRESS_CHECKSUM STRING(64) NOT NULL,
    VOLUME INT NOT NULL,
    NETFLOW INT NOT NULL,
    UP_NETFLOW INT DEFAULT NULL,
    DOWN_NETFLOW INT DEFAULT NULL,
    END_TIME TIMESTAMPTZ DEFAULT NULL
);

CREATE INDEX RECHARGE_ADDRESS ON CLIENT (RECHARGE_ADDRESS);

create table IF NOT EXISTS TRACKER(
    ID SERIAL PRIMARY KEY,
    SERVER STRING(64) NOT NULL,
    PORT INT NOT NULL,
    CATEGORY STRING(32)
);
