create table IF NOT EXISTS CLIENT(
    NODE_ID STRING(30) NOT NULL PRIMARY KEY, 
    PUBLIC_KEY BYTES NOT NULL,
    CONTACT_EMAIL STRING(128) NOT NULL,
    EMAIL_VERIFIED BOOL DEFAULT false,
    CREATION TIMESTAMPTZ NOT NULL,
    LAST_MODIFIED TIMESTAMPTZ NOT NULL,
    RANDOM_CODE STRING(8) DEFAULT NULL,
    SEND_TIME TIMESTAMPTZ DEFAULT NULL,
    ACTIVE BOOL NOT NULL DEFAULT true,
    REMOVED BOOL NOT NULL DEFAULT false,
    RECHARGE_ADDRESS STRING(64) DEFAULT NULL unique,
    ADDRESS_CHECKSUM STRING(64) DEFAULT NULL,
    BALANCE INT NOT NULL default 0,
    -- PACKAGE_LEVEL INT DEFAULT 0,
    PACKAGE_ID INT DEFAULT NULL REFERENCES PACKAGE(ID),
    VOLUME INT NOT NULL default 0,
    NETFLOW INT NOT NULL default 0,
    UP_NETFLOW INT NOT NULL default 0,
    DOWN_NETFLOW INT NOT NULL default 0,
    END_TIME TIMESTAMPTZ DEFAULT NULL
);

CREATE INDEX RECHARGE_ADDRESS ON CLIENT (RECHARGE_ADDRESS);

create table IF NOT EXISTS CLIENT_USAGE_AMOUNT(
    NODE_ID STRING(30) NOT NULL PRIMARY KEY REFERENCES CLIENT (NODE_ID),
    CREATION TIMESTAMPTZ NOT NULL,
    LAST_MODIFIED TIMESTAMPTZ NOT NULL,
    VOLUME INT NOT NULL default 0,
    NETFLOW INT NOT NULL default 0,
    UP_NETFLOW INT NOT NULL default 0,
    DOWN_NETFLOW INT NOT NULL default 0
);

create table IF NOT EXISTS TRACKER(
    ID SERIAL PRIMARY KEY,
    SERVER STRING(64) NOT NULL,
    PORT INT NOT NULL,  
    CATEGORY STRING(32)
);

create table IF NOT EXISTS CLIENT_DAILY_NETFLOW(
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    NODE_ID STRING(30) NOT NULL REFERENCES CLIENT (NODE_ID),
    DAY DATE NOT NULL,
    SERVICE_SEQ INT NOT NULL,
    UPSTREAM BOOL DEFAULT false,
    CREATION TIMESTAMPTZ NOT NULL,
    LAST_MODIFIED TIMESTAMPTZ NOT NULL,
    NETFLOW INT NOT NULL default 0,
    FIX_OFFSET INT NOT NULL default 0,
    UNIQUE (NODE_ID,DAY,SERVICE_SEQ,UPSTREAM)
);