// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

/*
Package forcollector_pb is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	ClientPubKeyReq
	ClientPubKeyResp
	ProviderPubKeyReq
	ProviderPubKeyResp
	HourlyUpdateReq
	HourlyUpdateResp
	ClientItem
	ProviderItem
	HourlySummary
	GetLastSummaryReq
	GetLastSummaryResp
*/
package forcollector_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ClientPubKeyReq struct {
	Timestamp uint64 `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Auth      []byte `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	NodeId    string `protobuf:"bytes,3,opt,name=nodeId" json:"nodeId,omitempty"`
}

func (m *ClientPubKeyReq) Reset()                    { *m = ClientPubKeyReq{} }
func (m *ClientPubKeyReq) String() string            { return proto.CompactTextString(m) }
func (*ClientPubKeyReq) ProtoMessage()               {}
func (*ClientPubKeyReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ClientPubKeyReq) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ClientPubKeyReq) GetAuth() []byte {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *ClientPubKeyReq) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

type ClientPubKeyResp struct {
	PubKeyEnc []byte `protobuf:"bytes,1,opt,name=pubKeyEnc,proto3" json:"pubKeyEnc,omitempty"`
}

func (m *ClientPubKeyResp) Reset()                    { *m = ClientPubKeyResp{} }
func (m *ClientPubKeyResp) String() string            { return proto.CompactTextString(m) }
func (*ClientPubKeyResp) ProtoMessage()               {}
func (*ClientPubKeyResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ClientPubKeyResp) GetPubKeyEnc() []byte {
	if m != nil {
		return m.PubKeyEnc
	}
	return nil
}

type ProviderPubKeyReq struct {
	Timestamp uint64 `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Auth      []byte `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	NodeId    string `protobuf:"bytes,3,opt,name=nodeId" json:"nodeId,omitempty"`
}

func (m *ProviderPubKeyReq) Reset()                    { *m = ProviderPubKeyReq{} }
func (m *ProviderPubKeyReq) String() string            { return proto.CompactTextString(m) }
func (*ProviderPubKeyReq) ProtoMessage()               {}
func (*ProviderPubKeyReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ProviderPubKeyReq) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ProviderPubKeyReq) GetAuth() []byte {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *ProviderPubKeyReq) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

type ProviderPubKeyResp struct {
	PubKeyEnc []byte `protobuf:"bytes,1,opt,name=pubKeyEnc,proto3" json:"pubKeyEnc,omitempty"`
}

func (m *ProviderPubKeyResp) Reset()                    { *m = ProviderPubKeyResp{} }
func (m *ProviderPubKeyResp) String() string            { return proto.CompactTextString(m) }
func (*ProviderPubKeyResp) ProtoMessage()               {}
func (*ProviderPubKeyResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ProviderPubKeyResp) GetPubKeyEnc() []byte {
	if m != nil {
		return m.PubKeyEnc
	}
	return nil
}

type HourlyUpdateReq struct {
	Timestamp uint64 `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Auth      []byte `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	Data      []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *HourlyUpdateReq) Reset()                    { *m = HourlyUpdateReq{} }
func (m *HourlyUpdateReq) String() string            { return proto.CompactTextString(m) }
func (*HourlyUpdateReq) ProtoMessage()               {}
func (*HourlyUpdateReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *HourlyUpdateReq) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *HourlyUpdateReq) GetAuth() []byte {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *HourlyUpdateReq) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type HourlyUpdateResp struct {
}

func (m *HourlyUpdateResp) Reset()                    { *m = HourlyUpdateResp{} }
func (m *HourlyUpdateResp) String() string            { return proto.CompactTextString(m) }
func (*HourlyUpdateResp) ProtoMessage()               {}
func (*HourlyUpdateResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type ClientItem struct {
	Upstream bool   `protobuf:"varint,1,opt,name=upstream" json:"upstream,omitempty"`
	NodeId   string `protobuf:"bytes,2,opt,name=nodeId" json:"nodeId,omitempty"`
	Day      string `protobuf:"bytes,3,opt,name=day" json:"day,omitempty"`
	Netflow  uint64 `protobuf:"varint,4,opt,name=netflow" json:"netflow,omitempty"`
}

func (m *ClientItem) Reset()                    { *m = ClientItem{} }
func (m *ClientItem) String() string            { return proto.CompactTextString(m) }
func (*ClientItem) ProtoMessage()               {}
func (*ClientItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ClientItem) GetUpstream() bool {
	if m != nil {
		return m.Upstream
	}
	return false
}

func (m *ClientItem) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *ClientItem) GetDay() string {
	if m != nil {
		return m.Day
	}
	return ""
}

func (m *ClientItem) GetNetflow() uint64 {
	if m != nil {
		return m.Netflow
	}
	return 0
}

type ProviderItem struct {
	Type    int32  `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	NodeId  string `protobuf:"bytes,2,opt,name=nodeId" json:"nodeId,omitempty"`
	Day     string `protobuf:"bytes,3,opt,name=day" json:"day,omitempty"`
	Netflow uint64 `protobuf:"varint,4,opt,name=netflow" json:"netflow,omitempty"`
}

func (m *ProviderItem) Reset()                    { *m = ProviderItem{} }
func (m *ProviderItem) String() string            { return proto.CompactTextString(m) }
func (*ProviderItem) ProtoMessage()               {}
func (*ProviderItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ProviderItem) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *ProviderItem) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *ProviderItem) GetDay() string {
	if m != nil {
		return m.Day
	}
	return ""
}

func (m *ProviderItem) GetNetflow() uint64 {
	if m != nil {
		return m.Netflow
	}
	return 0
}

type HourlySummary struct {
	Last         int64           `protobuf:"varint,1,opt,name=last" json:"last,omitempty"`
	Start        int64           `protobuf:"varint,2,opt,name=start" json:"start,omitempty"`
	ClientItem   []*ClientItem   `protobuf:"bytes,3,rep,name=clientItem" json:"clientItem,omitempty"`
	ProviderItem []*ProviderItem `protobuf:"bytes,4,rep,name=providerItem" json:"providerItem,omitempty"`
}

func (m *HourlySummary) Reset()                    { *m = HourlySummary{} }
func (m *HourlySummary) String() string            { return proto.CompactTextString(m) }
func (*HourlySummary) ProtoMessage()               {}
func (*HourlySummary) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *HourlySummary) GetLast() int64 {
	if m != nil {
		return m.Last
	}
	return 0
}

func (m *HourlySummary) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *HourlySummary) GetClientItem() []*ClientItem {
	if m != nil {
		return m.ClientItem
	}
	return nil
}

func (m *HourlySummary) GetProviderItem() []*ProviderItem {
	if m != nil {
		return m.ProviderItem
	}
	return nil
}

type GetLastSummaryReq struct {
	Timestamp uint64 `protobuf:"varint,1,opt,name=timestamp" json:"timestamp,omitempty"`
	Auth      []byte `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
}

func (m *GetLastSummaryReq) Reset()                    { *m = GetLastSummaryReq{} }
func (m *GetLastSummaryReq) String() string            { return proto.CompactTextString(m) }
func (*GetLastSummaryReq) ProtoMessage()               {}
func (*GetLastSummaryReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GetLastSummaryReq) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *GetLastSummaryReq) GetAuth() []byte {
	if m != nil {
		return m.Auth
	}
	return nil
}

type GetLastSummaryResp struct {
	LastSummary int64 `protobuf:"varint,1,opt,name=lastSummary" json:"lastSummary,omitempty"`
}

func (m *GetLastSummaryResp) Reset()                    { *m = GetLastSummaryResp{} }
func (m *GetLastSummaryResp) String() string            { return proto.CompactTextString(m) }
func (*GetLastSummaryResp) ProtoMessage()               {}
func (*GetLastSummaryResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *GetLastSummaryResp) GetLastSummary() int64 {
	if m != nil {
		return m.LastSummary
	}
	return 0
}

func init() {
	proto.RegisterType((*ClientPubKeyReq)(nil), "forcollector.pb.ClientPubKeyReq")
	proto.RegisterType((*ClientPubKeyResp)(nil), "forcollector.pb.ClientPubKeyResp")
	proto.RegisterType((*ProviderPubKeyReq)(nil), "forcollector.pb.ProviderPubKeyReq")
	proto.RegisterType((*ProviderPubKeyResp)(nil), "forcollector.pb.ProviderPubKeyResp")
	proto.RegisterType((*HourlyUpdateReq)(nil), "forcollector.pb.HourlyUpdateReq")
	proto.RegisterType((*HourlyUpdateResp)(nil), "forcollector.pb.HourlyUpdateResp")
	proto.RegisterType((*ClientItem)(nil), "forcollector.pb.ClientItem")
	proto.RegisterType((*ProviderItem)(nil), "forcollector.pb.ProviderItem")
	proto.RegisterType((*HourlySummary)(nil), "forcollector.pb.HourlySummary")
	proto.RegisterType((*GetLastSummaryReq)(nil), "forcollector.pb.GetLastSummaryReq")
	proto.RegisterType((*GetLastSummaryResp)(nil), "forcollector.pb.GetLastSummaryResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ForCollectorService service

type ForCollectorServiceClient interface {
	ClientPubKey(ctx context.Context, in *ClientPubKeyReq, opts ...grpc.CallOption) (*ClientPubKeyResp, error)
	ProviderPubKey(ctx context.Context, in *ProviderPubKeyReq, opts ...grpc.CallOption) (*ProviderPubKeyResp, error)
	HourlyUpdate(ctx context.Context, in *HourlyUpdateReq, opts ...grpc.CallOption) (*HourlyUpdateResp, error)
	GetLastSummary(ctx context.Context, in *GetLastSummaryReq, opts ...grpc.CallOption) (*GetLastSummaryResp, error)
}

type forCollectorServiceClient struct {
	cc *grpc.ClientConn
}

func NewForCollectorServiceClient(cc *grpc.ClientConn) ForCollectorServiceClient {
	return &forCollectorServiceClient{cc}
}

func (c *forCollectorServiceClient) ClientPubKey(ctx context.Context, in *ClientPubKeyReq, opts ...grpc.CallOption) (*ClientPubKeyResp, error) {
	out := new(ClientPubKeyResp)
	err := grpc.Invoke(ctx, "/forcollector.pb.ForCollectorService/ClientPubKey", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forCollectorServiceClient) ProviderPubKey(ctx context.Context, in *ProviderPubKeyReq, opts ...grpc.CallOption) (*ProviderPubKeyResp, error) {
	out := new(ProviderPubKeyResp)
	err := grpc.Invoke(ctx, "/forcollector.pb.ForCollectorService/ProviderPubKey", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forCollectorServiceClient) HourlyUpdate(ctx context.Context, in *HourlyUpdateReq, opts ...grpc.CallOption) (*HourlyUpdateResp, error) {
	out := new(HourlyUpdateResp)
	err := grpc.Invoke(ctx, "/forcollector.pb.ForCollectorService/HourlyUpdate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forCollectorServiceClient) GetLastSummary(ctx context.Context, in *GetLastSummaryReq, opts ...grpc.CallOption) (*GetLastSummaryResp, error) {
	out := new(GetLastSummaryResp)
	err := grpc.Invoke(ctx, "/forcollector.pb.ForCollectorService/GetLastSummary", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ForCollectorService service

type ForCollectorServiceServer interface {
	ClientPubKey(context.Context, *ClientPubKeyReq) (*ClientPubKeyResp, error)
	ProviderPubKey(context.Context, *ProviderPubKeyReq) (*ProviderPubKeyResp, error)
	HourlyUpdate(context.Context, *HourlyUpdateReq) (*HourlyUpdateResp, error)
	GetLastSummary(context.Context, *GetLastSummaryReq) (*GetLastSummaryResp, error)
}

func RegisterForCollectorServiceServer(s *grpc.Server, srv ForCollectorServiceServer) {
	s.RegisterService(&_ForCollectorService_serviceDesc, srv)
}

func _ForCollectorService_ClientPubKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientPubKeyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForCollectorServiceServer).ClientPubKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/forcollector.pb.ForCollectorService/ClientPubKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForCollectorServiceServer).ClientPubKey(ctx, req.(*ClientPubKeyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForCollectorService_ProviderPubKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProviderPubKeyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForCollectorServiceServer).ProviderPubKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/forcollector.pb.ForCollectorService/ProviderPubKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForCollectorServiceServer).ProviderPubKey(ctx, req.(*ProviderPubKeyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForCollectorService_HourlyUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HourlyUpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForCollectorServiceServer).HourlyUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/forcollector.pb.ForCollectorService/HourlyUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForCollectorServiceServer).HourlyUpdate(ctx, req.(*HourlyUpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForCollectorService_GetLastSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLastSummaryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForCollectorServiceServer).GetLastSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/forcollector.pb.ForCollectorService/GetLastSummary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForCollectorServiceServer).GetLastSummary(ctx, req.(*GetLastSummaryReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ForCollectorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "forcollector.pb.ForCollectorService",
	HandlerType: (*ForCollectorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClientPubKey",
			Handler:    _ForCollectorService_ClientPubKey_Handler,
		},
		{
			MethodName: "ProviderPubKey",
			Handler:    _ForCollectorService_ProviderPubKey_Handler,
		},
		{
			MethodName: "HourlyUpdate",
			Handler:    _ForCollectorService_HourlyUpdate_Handler,
		},
		{
			MethodName: "GetLastSummary",
			Handler:    _ForCollectorService_GetLastSummary_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 478 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0x63, 0xb7, 0x34, 0x53, 0x43, 0xd2, 0x01, 0x21, 0xab, 0x80, 0x64, 0x96, 0x4b, 0x4e,
	0x11, 0x0a, 0x12, 0x17, 0x4e, 0xa8, 0x2a, 0x50, 0xc1, 0xa1, 0xda, 0x2a, 0xe2, 0x50, 0x71, 0xd8,
	0xd8, 0x1b, 0x61, 0xc9, 0xce, 0x2e, 0xbb, 0xeb, 0x22, 0xff, 0x34, 0x7e, 0x1c, 0x12, 0xca, 0xe4,
	0xc3, 0x76, 0x92, 0x2a, 0x52, 0x45, 0x6f, 0x33, 0xa3, 0x9d, 0xf7, 0xde, 0x3c, 0xcf, 0x18, 0xba,
	0x42, 0x67, 0x43, 0x6d, 0x94, 0x53, 0xd8, 0x9b, 0x2a, 0x93, 0xa8, 0x3c, 0x97, 0x89, 0x53, 0x66,
	0xa8, 0x27, 0xec, 0x06, 0x7a, 0xe7, 0x79, 0x26, 0x67, 0xee, 0xaa, 0x9c, 0x7c, 0x95, 0x15, 0x97,
	0xbf, 0xf0, 0x25, 0x74, 0x5d, 0x56, 0x48, 0xeb, 0x44, 0xa1, 0x23, 0x2f, 0xf6, 0x06, 0x01, 0xaf,
	0x0b, 0x88, 0x10, 0x88, 0xd2, 0xfd, 0x8c, 0x3a, 0xb1, 0x37, 0x08, 0x39, 0xc5, 0xf8, 0x1c, 0x8e,
	0x66, 0x2a, 0x95, 0x97, 0x69, 0xe4, 0xc7, 0xde, 0xa0, 0xcb, 0x97, 0x19, 0x7b, 0x0b, 0xfd, 0x36,
	0xb8, 0xd5, 0x73, 0x74, 0x4d, 0xd9, 0xc5, 0x2c, 0x21, 0xf4, 0x90, 0xd7, 0x05, 0xf6, 0x03, 0x4e,
	0xaf, 0x8c, 0xba, 0xcd, 0x52, 0x69, 0x1e, 0x42, 0xd0, 0x08, 0x70, 0x13, 0x7e, 0xaf, 0xa4, 0xef,
	0xd0, 0xfb, 0xa2, 0x4a, 0x93, 0x57, 0x63, 0x9d, 0x0a, 0x27, 0xef, 0x27, 0x08, 0x21, 0x48, 0x85,
	0x13, 0x24, 0x27, 0xe4, 0x14, 0x33, 0x84, 0x7e, 0x1b, 0xd8, 0x6a, 0x96, 0x03, 0x2c, 0x1c, 0xbb,
	0x74, 0xb2, 0xc0, 0x33, 0x38, 0x2e, 0xb5, 0x75, 0x46, 0x8a, 0x82, 0x68, 0x8e, 0xf9, 0x3a, 0x6f,
	0x8c, 0xd8, 0x69, 0x8e, 0x88, 0x7d, 0xf0, 0x53, 0x51, 0x2d, 0xe7, 0x9e, 0x87, 0x18, 0xc1, 0xa3,
	0x99, 0x74, 0xd3, 0x5c, 0xfd, 0x8e, 0x02, 0xd2, 0xba, 0x4a, 0xd9, 0x14, 0xc2, 0x95, 0x1d, 0xc4,
	0x87, 0x10, 0xb8, 0x4a, 0x4b, 0xe2, 0x3a, 0xe4, 0x14, 0xff, 0x17, 0x9e, 0x3f, 0x1e, 0x3c, 0x5e,
	0x8c, 0x7a, 0x5d, 0x16, 0x85, 0x30, 0xd5, 0x9c, 0x29, 0x17, 0xd6, 0x11, 0x93, 0xcf, 0x29, 0xc6,
	0x67, 0x70, 0x68, 0x9d, 0x30, 0x8e, 0x88, 0x7c, 0xbe, 0x48, 0xf0, 0x03, 0x40, 0xb2, 0x76, 0x24,
	0xf2, 0x63, 0x7f, 0x70, 0x32, 0x7a, 0x31, 0xdc, 0x58, 0xe3, 0x61, 0x6d, 0x1a, 0x6f, 0x3c, 0xc7,
	0x8f, 0x10, 0xea, 0xc6, 0x80, 0x51, 0x40, 0xed, 0xaf, 0xb6, 0xda, 0x9b, 0x2e, 0xf0, 0x56, 0x0b,
	0xbb, 0x80, 0xd3, 0xcf, 0xd2, 0x7d, 0x13, 0xd6, 0x2d, 0xb5, 0xdf, 0x6b, 0x01, 0xd8, 0x7b, 0xc0,
	0x4d, 0x18, 0xab, 0x31, 0x86, 0x93, 0xbc, 0x2e, 0x2d, 0xdd, 0x68, 0x96, 0x46, 0x7f, 0x3b, 0xf0,
	0xf4, 0x93, 0x32, 0xe7, 0x2b, 0xb5, 0xd7, 0xd2, 0xdc, 0x66, 0x89, 0xc4, 0x31, 0x84, 0xcd, 0xd3,
	0xc2, 0xf8, 0x0e, 0x4b, 0xd6, 0x57, 0x74, 0xf6, 0x7a, 0xcf, 0x0b, 0xab, 0xd9, 0x01, 0xde, 0xc0,
	0x93, 0xf6, 0x81, 0x20, 0xbb, 0xd3, 0xac, 0x1a, 0xfa, 0xcd, 0xde, 0x37, 0x04, 0x3e, 0x86, 0xb0,
	0xb9, 0xf0, 0x3b, 0x34, 0x6f, 0x1c, 0xda, 0x0e, 0xcd, 0x5b, 0x17, 0x43, 0x9a, 0xdb, 0xd6, 0xee,
	0xd0, 0xbc, 0xf5, 0x09, 0x77, 0x68, 0xde, 0xfe, 0x3e, 0xec, 0x60, 0x72, 0x44, 0xff, 0xcd, 0x77,
	0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x90, 0xf4, 0x93, 0x1b, 0x44, 0x05, 0x00, 0x00,
}
