// Code generated by mockery v1.0.0
package impl

import db "nebula-tracker/db"

import mock "github.com/stretchr/testify/mock"

// chooserMock is an autogenerated mock type for the chooserMock type
type chooserMock struct {
	mock.Mock
}

// Choose provides a mock function with given fields: num
func (_m *chooserMock) Choose(num int) []db.ProviderInfo {
	ret := _m.Called(num)

	var r0 []db.ProviderInfo
	if rf, ok := ret.Get(0).(func(int) []db.ProviderInfo); ok {
		r0 = rf(num)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.ProviderInfo)
		}
	}

	return r0
}

// Count provides a mock function with given fields:
func (_m *chooserMock) Count() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}
